env: "local" # Окружение - local, dev или prod
#storage_path: "./storage/storage.db" # файл, в котором будет храниться наша БД
storage_path: "./storage.db" # перенес в папку с файлом main.go
http_server: # конфигурация нашего http-сервера
  address: "localhost:8082"
  # in future Добавил к iter9
  file_repo: "pip.json"
  timeout: 4s
  idle_timeout: 30s